import{a as h,S as f,i as d}from"./assets/vendor-2304a7e8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(t){if(t.ep)return;t.ep=!0;const a=r(t);fetch(t.href,a)}})();async function m(o,e,r){try{const i="https://pixabay.com",t="/api/";h.defaults.baseURL=i;const a={key:"45227925-dc4eec2d8e9c6a7da21dc7ebe",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:r},n=await h.get(t,{params:a});return console.log(n.data),n.data}catch(i){throw iziToast.error({title:"Error",message:`${i}`,layout:2,position:"topRight",displayMode:"once"}),i}}const S=new f(".gallery li",{captionsData:"alt",captionDelay:250});function y(o){const e=o.map(r=>`<li class="gallery-item"
      <a class="gallery-link" href="${r.largeImageURL}">
    <img
      width=360;
      height=200;
      class="gallery-image"
      src="${r.webformatURL}"
      alt="${r.tags} " />
          <div class="image-info">
               <p>LIKES: ${r.likes}</p>
                    <p>VIEWS: ${r.views}</p>
                    <p>COMMENTS: ${r.comments}</p>
                    <p>DOWNLOADS: ${r.downloads}</p>
                </div>
            </a>
            </li>
        `).join("");s.imgGallery.insertAdjacentHTML("beforeend",e),S.refresh()}function L(){s.loader.classList.remove("hidden")}function u(){s.loader.classList.add("hidden")}function b(){s.loadMoreBtn.classList.remove("hidden")}function p(){s.loadMoreBtn.classList.add("hidden")}function w(o,e){o>=e?(p(),e&&iziToast.info({title:"The end!",message:"We're sorry, but you've reached the end of search results."})):b()}let c="",l=1,g=15,B=1;const s={formSearch:document.querySelector("#search"),inputImgSearch:document.querySelector(".input-img-search"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},M=new f(".gallery li",{captionsData:"alt",captionDelay:250});function E(o=0,e=0){const r=s.imgGallery.children[0];if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,left:e,behavior:"smooth"})}}s.formSearch.addEventListener("submit",async o=>{if(o.preventDefault(),console.log("Form submit handler triggered"),s.imgGallery.innerHTML="",c=o.target.elements.search.value.trim(),l=1,p(),c===""){d.warning({title:"Warning",message:"Please, enter the query.",backgroundColor:"#ef4040",layout:2,position:"topRight",displayMode:"once"}),s.formSearch.reset();return}L();try{const e=await m(c,l,g);if(B=Math.ceil(e.totalHits/g),e.totalHits===0){d.error({message:"Sorry, there are no images matching your search query. Please try again!",layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"}),u();return}y(e.hits),M.refresh(),u(),console.log("Calling showLoadMore()"),b()}catch(e){d.error({title:"Error",message:`${e}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});s.loadMoreBtn.addEventListener("click",async()=>{l++,console.log("Current Page:",l),console.log("Input Value:",c),p(),L();try{const o=await m(c,l,g);y(o.hits),M.refresh(),u(),w(l,B),E()}catch(o){d.error({title:"Error",message:`${o}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
